# Generated by Django 4.1.5 on 2023-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
